
export const BottomsData = [
    {
        id: 11,
        tittle: "Skinny Fit Jeans",
        size: ["S", "M", "L"],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        price: 59.99,
        image: "/jeans1.png",
        category: ["new arrival", "discount", "jeans", "casual", 'party'],
        style: "Casual",
        color: "Blue",
        rating: 3.5,
        discount: 20,
        slug: 'products/bottoms/',
    },
    {
        id: 12,
        tittle: "Faded Skinny Jeans",
        size: ["S", "M", "L"],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        price: 49.99,
        image: "/jeans2.png",
        category: ["jeans", "top selling", "formal"],
        style: "Formal",
        color: "Black",
        rating: 4.5,
        discount: 0,
        slug: 'products/bottoms/',
    },
    {
        id: 13,
        tittle: "Loose Fit Bermuda Shorts",
        size: ["S", "M", "L"],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        price: 29.99,
        image: "/shorts1.png",
        category: ["new arrival", "shorts", "top selling", "casual", 'party'],
        style: "Casual",
        color: "Blue",
        rating: 4.0,
        discount: 0,
        slug: 'products/bottoms/',
    }
]