export const Reviews = [
    {
        id: 1,
        category: "tops",
        itemID: 1,
        description: "Very stylish and breathable. Wore it out and got lots of compliments!",
        score: 4.0,
        name: "Ava M.",
        date: "2023-12-01",
    },
    {
        id: 2,
        category: "tops",
        itemID: 1,
        description: "Super comfortable and looks just like the picture. Definitely recommend it!",
        score: 4.5,
        name: "Emily C.",
        date: "2023-10-12",
    },
    {
        id: 7,
        category: "tops",
        itemID: 2,
        description: "Perfect fit and the material is soft. Feels great for casual wear.",
        score: 4.0,
        name: "Noah K.",
        date: "2023-11-10",
    },
    {
        id: 8,
        category: "tops",
        itemID: 2,
        description: "Nice shirt but I expected the color to be a bit brighter. Still decent.",
        score: 3.0,
        name: "Isabella R.",
        date: "2023-11-18",
    },
    {
        id: 9,
        category: "tops",
        itemID: 2,
        description: "Quality exceeded my expectations. Will definitely buy again.",
        score: 5.0,
        name: "Ethan W.",
        date: "2023-12-04",
    },
    {
        id: 10,
        category: "tops",
        itemID: 2,
        description: "Not bad overall. It shrank slightly after washing, so wash with care.",
        score: 3.0,
        name: "Mia T.",
        date: "2023-12-11",
    },
    {
        id: 11,
        category: "tops",
        itemID: 2,
        description: "Stylish and fits well. Got compliments the first time I wore it.",
        score: 4.5,
        name: "Jackson R.",
        date: "2023-12-20",
    },
    {
        id: 12,
        category: "tops",
        itemID: 3,
        description: "Comfortable and affordable. Good for daily wear.",
        score: 4,
        name: "Olivia G.",
        date: "2024-01-05",
    },
    {
        id: 13,
        category: "tops",
        itemID: 3,
        description: "Material is a bit thin, but still wearable.",
        score: 3.5,
        name: "Luca H.",
        date: "2024-01-12",
    },
    {
        id: 14,
        category: "tops",
        itemID: 4,
        description: "The color fades quickly after a few washes.",
        score: 3,
        name: "Zoe B.",
        date: "2024-01-20",
    },
    {
        id: 15,
        category: "tops",
        itemID: 4,
        description: "Decent quality and fits nicely.",
        score: 4,
        name: "James A.",
        date: "2024-01-27",
    },
    {
        id: 16,
        category: "tops",
        itemID: 5,
        description: "Love the design and it fits true to size.",
        score: 4.5,
        name: "Amelia S.",
        date: "2024-02-02",
    },
    {
        id: 17,
        category: "tops",
        itemID: 5,
        description: "Average shirt, nothing special.",
        score: 3,
        name: "Henry P.",
        date: "2024-02-10",
    },
    {
        id: 18,
        category: "tops",
        itemID: 6,
        description: "Excellent fabric and comfortable all day long.",
        score: 4.5,
        name: "Ella A.",
        date: "2024-02-18",
    },
    {
        id: 19,
        category: "tops",
        itemID: 6,
        description: "Runs a little tight. Order one size up.",
        score: 3.5,
        name: "Benjamin R.",
        date: "2024-02-24",
    },
    {
        id: 20,
        category: "tops",
        itemID: 7,
        description: "Not impressed. Wouldn't buy again.",
        score: 2.5,
        name: "Chloe M.",
        date: "2024-03-01",
    },
    {
        id: 21,
        category: "tops",
        itemID: 7,
        description: "Okay for the price, but stitching could be better.",
        score: 3,
        name: "Sebastian C.",
        date: "2024-03-09",
    },
    {
        id: 22,
        category: "tops",
        itemID: 8,
        description: "Fits well and stylish. I like it!",
        score: 4,
        name: "Layla W.",
        date: "2024-03-14",
    },
    {
        id: 23,
        category: "tops",
        itemID: 8,
        description: "Washes well and keeps shape.",
        score: 4.5,
        name: "Aiden P.",
        date: "2024-03-20",
    },
    {
        id: 24,
        category: "tops",
        itemID: 9,
        description: "Too basic for my taste, but not bad.",
        score: 3,
        name: "Grace B.",
        date: "2024-03-28",
    },
    {
        id: 25,
        category: "tops",
        itemID: 9,
        description: "Soft and breathable. Great for summer.",
        score: 4.5,
        name: "Jack M.",
        date: "2024-04-04",
    },
    {
        id: 26,
        category: "tops",
        itemID: 10,
        description: "Exactly what I was looking for.",
        score: 4,
        name: "Scarlett H.",
        date: "2024-04-10",
    },
    {
        id: 27,
        category: "tops",
        itemID: 10,
        description: "A little overpriced for the quality.",
        score: 3.5,
        name: "Daniel F.",
        date: "2024-04-17",
    },

    {
        id: 28,
        category: "bottoms",
        itemID: 11,
        description: "Solid pair of jeans. Fits well and feels durable.",
        score: 4,
        name: "Natalie B",
        date: "2024-04-22",
    },
    {
        id: 29,
        category: "bottoms",
        itemID: 11,
        description: "Nice style, but the waist is a bit tight.",
        score: 3.5,
        name: "Connor H.",
        date: "2024-04-28",
    },
    {
        id: 30,
        category: "bottoms",
        itemID: 12,
        description: "Perfect everyday jeans. Very comfortable and stretchy.",
        score: 4.5,
        name: "Sienna F.",
        date: "2024-05-02",
    },
    {
        id: 31,
        category: "bottoms",
        itemID: 12,
        description: "Not bad, but I expected a darker wash.",
        score: 3.5,
        name: "Dylan P.",
        date: "2024-05-08",
    },
    {
        id: 32,
        category: "bottoms",
        itemID: 13,
        description: "Light and breathable—great for hot days.",
        score: 4.5,
        name: "Hailey R.",
        date: "2024-05-12",
    },
    {
        id: 33,
        category: "bottoms",
        itemID: 13,
        description: "Good fit but a little short for my taste.",
        score: 3,
        name: "Owen B.",
        date: "2024-05-18",
    }

]