export const TopsData = [
    {
        id: 1,
        tittle: "Vertical Striped Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 49.99,
        image: "/shirt1.png",
        category: ["new arrival", "shirt", "discount", "top selling"],
        style: "Formal",
        color: "Green",
        rating: 5.0,
        discount: 20,
    },
    {
        id: 2,
        tittle: "T-shirt with Tape Details",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 39.99,
        image: "/shirt2.png",
        category: ["shirt"],
        style: "Casual",
        color: "Black",
        rating: 4.5,
        discount: 0,
    },
    {
        id: 3,
        tittle: "Courage Graphic T-shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 49.99,
        image: "/shirt3.png",
        category: ["shirt"],
        style: "Casual",
        color: "Orange",
        rating: 4.0,
        discount: 0,
    },
    {
        id: 4,
        tittle: "Checkered Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 29.99,
        image: "/shirt4.png",
        category: ["shirt", "top selling"],
        style: "Formal",
        color: "Red",
        rating: 4.5,
        discount: 0,
    },
    {
        id: 5,
        tittle: "Sleeve Striped T-hirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 39.99,
        image: "/shirt5.png",
        category: ["new arrival", "shirt"],
        style: "Casual",
        color: "Orange",
        rating: 4.5,
        discount: 0,
    },
    {
        id: 6,
        tittle: "One Life Graphic T-shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 39.99,
        image: "/shirt6.png",
        category: ["shirt", "discount"],
        style: "Casual",
        color: "Green",
        rating: 4.5,
        discount: 40,
    },
    {
        id: 7,
        tittle: "Polo with Contrast Trims",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 49.99,
        image: "/shirt7.png",
        category: ["shirt"],
        style: "Casual",
        color: "Blue",
        rating: 4.0,
        discount: 0,
    },
    {
        id: 8,
        tittle: "Gradient Graphic T-shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 49.99,
        image: "/shirt8.png",
        category: ["shirt", "top selling"],
        style: "Casual",
        color: "White",
        rating: 3.5,
        discount: 0,
    },
    {
        id: 9,
        tittle: "Polo with Tipping Details",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 49.99,
        image: "/shirt9.png",
        category: ["new arrival", "shirt", "top selling"],
        style: "Casual",
        color: "Pink",
        rating: 4.5,
        discount: 0,
    },
    {
        id: 10,
        tittle: "Black Striped T-shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi mollitia, praesentium corporis omnis non rerum nobis eos dicta, laborum",
        size: ["S", "M", "L", "XL"],
        price: 59.99,
        image: "/shirt10.png",
        category: ["shirt"],
        style: "Casual",
        color: "white",
        rating: 5.0,
        discount: 0,
    },
]